// Single-process entrypoint since #52: pantry-web is now the only
// long-running process for the whole system, so this registers the ops
// jobs that used to live in the bot's own entrypoint (heartbeat, nightly
// snapshot cron — deleted along with the bot in #51) before starting the
// Mini App server itself. Ops wiring runs first and unconditionally, unlike
// an Astro middleware/route import, which only loads on a request — with
// two users and long idle stretches, that could delay the nightly cron's
// registration by hours.
import { loadConfig } from "./config.js";
import { createDb } from "./db.js";
import { startHeartbeat } from "./heartbeat.js";
import { scheduleNightlySnapshot } from "./snapshot.js";

const config = loadConfig();
const db = createDb(config.dbPath);

startHeartbeat(config.heartbeatPath, config.heartbeatIntervalMs);
scheduleNightlySnapshot(db.$client, config.snapshotPath, config.snapshotCron, config.tz);

// Astro's own build output, generated by `pnpm web:build` — not part of
// this project's rootDir/tsconfig, so TS can't (and shouldn't) resolve a
// declaration for it.
const astroEntryPath = "../web/dist/server/entry.mjs";
await import(astroEntryPath);
